export const movies = [
  {
    id: 1,
    title: "The Big Swallow",
    year: 1901,
    director: "James Williamson",
    rating: 5,
  },
  {
    id: 2,
    title: "A Corner in Wheat",
    year: 1909,
    director: "D.W. Griffith",
    rating: 5,
  },
  {
    id: 3,
    title: "Little Nemo",
    year: 1911,
    director: "Winsor McCay",
    rating: 6,
  },
  {
    id: 4,
    title: "Dante's Inferno",
    year: 1911,
    director: "Giuseppe de Liguoro",
    rating: 5,
  },
  {
    id: 5,
    title: "The Cameraman's Revenge",
    year: 1912,
    director: "Wladyslaw Starewicz",
    rating: 6,
  },
  {
    id: 6,
    title: "Fantômas",
    year: 1913,
    director: "Louis Feuillade ",
    rating: 6,
  },
  {
    id: 7,
    title: "The Student of Prague",
    year: 1913,
    director: "Stellan Rye",
    rating: 6,
  },
  {
    id: 8,
    title: "Drama on the Volga",
    year: 1913,
    director: "Nikolai Larin",
    rating: 6,
  },
  {
    id: 9,
    title: "Ingeborg Holm",
    year: 1913,
    director: "Victor Sjöström",
    rating: 5,
  },
  {
    id: 10,
    title: "The Mysterious X",
    year: 1914,
    director: "Benjamin Christensen",
    rating: 5,
  },
  {
    id: 11,
    title: "Zapata's Gang",
    year: 1914,
    director: "Urban Gad",
    rating: 5,
  },
  {
    id: 12,
    title: "Maciste",
    year: 1915,
    director: "Vincenzo Denizot",
    rating: 7,
  },
  {
    id: 13,
    title: "The Vampires or, The Arch Criminals of Paris",
    year: 1915,
    director: "Louis Feuillade",
    rating: 6,
  },
  {
    id: 14,
    title: "Filibus",
    year: 1915,
    director: "Mario Roncoroni",
    rating: 5,
  },
  {
    id: 15,
    title: "The Regeneration",
    year: 1915,
    director: "Raoul Walsh",
    rating: 5,
  },
  {
    id: 16,
    title: "Alias Jimmy Valentine",
    year: 1915,
    director: "Maurice Tourneur",
    rating: 5,
  },
  {
    id: 17,
    title: "Flirting with Fate",
    year: 1916,
    director: "Christy Cabanne",
    rating: 6,
  },
  {
    id: 18,
    title: "Intolerance: Love's Struggle Throughout the Ages",
    year: 1916,
    director: "D.W. Griffith",
    rating: 6,
  },
  {
    id: 19,
    title: "Shoes",
    year: 1916,
    director: "Lois Weber",
    rating: 5,
  },
  {
    id: 20,
    title: "Hell's Hinges",
    year: 1916,
    director: "Charles Swickard",
    rating: 6,
  },
  {
    id: 21,
    title: "For Happiness",
    year: 1917,
    director: "Yevgeni Bauer",
    rating: 7,
  },
  {
    id: 22,
    title: "The Poor Little Rich Girl",
    year: 1917,
    director: "Maurice Tourneur",
    rating: 7,
  },
  {
    id: 23,
    title: "Wild and Woolly",
    year: 1917,
    director: "John Emerson",
    rating: 6,
  },
  {
    id: 24,
    title: "The Dying Swan",
    year: 1917,
    director: "Yevgeni Bauer",
    rating: 6,
  },
  {
    id: 25,
    title: "Thaïs",
    year: 1917,
    director: "Anton Giulio Bragaglia",
    rating: 8,
  },
  {
    id: 26,
    title: "Amarilly of Clothes-Line Alley",
    year: 1918,
    director: "Marshall Neilan",
    rating: 6,
  },
  {
    id: 27,
    title: "Hell Bent",
    year: 1918,
    director: "John Ford ",
    rating: 5,
  },
  {
    id: 28,
    title: "The Blue Bird",
    year: 1918,
    director: "Maurice Tourneur ",
    rating: 9,
  },
  {
    id: 29,
    title: "Night Music",
    year: 1918,
    director: "Georg af Klercker",
    rating: 5,
  },
  {
    id: 30,
    title: "Thomas Graal's Best Child",
    year: 1918,
    director: "Mauritz Stiller",
    rating: 6,
  },
  {
    id: 31,
    title: "Stella Maris",
    year: 1918,
    director: "Marshall Neilan",
    rating: 5,
  },
  {
    id: 32,
    title: "The Doll",
    year: 1919,
    director: "Ernst Lubitsch",
    rating: 7,
  },
  {
    id: 33,
    title: "Sir Arne's Treasure",
    year: 1919,
    director: "Mauritz Stiller",
    rating: 5,
  },
  {
    id: 34,
    title: "When the Clouds Roll By",
    year: 1919,
    director: "Victor Fleming",
    rating: 5,
  },
  {
    id: 35,
    title: "Male and Female",
    year: 1919,
    director: "Cecil B. DeMille",
    rating: 8,
  },
  {
    id: 36,
    title: "Blind Husbands",
    year: 1919,
    director: "Erich von Stroheim",
    rating: 5,
  },
  {
    id: 37,
    title: "Victory",
    year: 1919,
    director: "Maurice Tourneur",
    rating: 6,
  },
  {
    id: 38,
    title: "Bumping Into Broadway",
    year: 1919,
    director: "Hal Roach",
    rating: 5,
  },
  {
    id: 39,
    title: "J'accuse",
    year: 1919,
    director: "Abel Gance",
    rating: 6,
  },
  {
    id: 40,
    title: "Sons of Ingmar",
    year: 1919,
    director: "Victor Sjöström",
    rating: 6,
  },
  {
    id: 41,
    title: "Song of the Scarlet Flower",
    year: 1919,
    director: "Mauritz Stiller",
    rating: 6,
  },
  {
    id: 42,
    title: "South",
    year: 1919,
    director: "Frank Hurley",
    rating: 5,
  },
  {
    id: 43,
    title: "One Week",
    year: 1920,
    director: "Buster Keaton",
    rating: 8,
  },
  {
    id: 44,
    title: "Neighbors",
    year: 1920,
    director: "Buster Keaton",
    rating: 7,
  },
  {
    id: 45,
    title: "The Scarecrow",
    year: 1920,
    director: "Edward F. Cline",
    rating: 6,
  },
  {
    id: 46,
    title: "Convict 13",
    year: 1920,
    director: "Buster Keaton",
    rating: 5,
  },
  {
    id: 47,
    title: "Romeo and Juliet in the Snow",
    year: 1920,
    director: "Ernst Lubitsch",
    rating: 8,
  },
  {
    id: 49,
    title: "The Cabinet of Dr. Caligari",
    year: 1920,
    director: "Robert Wiene",
    rating: 6,
  },
  {
    id: 50,
    title: "The Parson's Widow",
    year: 1920,
    director: "Carl Theodor Dreyer",
    rating: 6,
  },
  {
    id: 51,
    title: "Kohlhiesel's Daughters",
    year: 1920,
    director: "Ernst Lubitsch",
    rating: 5,
  },
  {
    id: 52,
    title: "Way Down East",
    year: 1920,
    director: "D.W. Griffith",
    rating: 6,
  },
  {
    id: 53,
    title: "Fante-Anne",
    year: 1920,
    director: "Rasmus Breistein",
    rating: 7,
  },
  {
    id: 54,
    title: "Erotikon",
    year: 1920,
    director: "Mauritz Stiller",
    rating: 6,
  },
  {
    id: 55,
    title: "Leaves from Satan's Book",
    year: 1920,
    director: "Carl Theodor Dreyer",
    rating: 5,
  },
  {
    id: 56,
    title: "The Man of the Sea",
    year: 1920,
    director: "Marcel L'Herbier",
    rating: 5,
  },
  {
    id: 57,
    title: "Anna Boleyn",
    year: 1920,
    director: "Ernst Lubitsch",
    rating: 5,
  },
  {
    id: 58,
    title: "Suds",
    year: 1920,
    director: "John Francis Dillon",
    rating: 5,
  },
  {
    id: 59,
    title: "Fièvre",
    year: 1921,
    director: "Louis Delluc",
    rating: 5,
  },
  {
    id: 60,
    title: "The Haunted House",
    year: 1921,
    director: "Edward F. Cline",
    rating: 6,
  },
  {
    id: 61,
    title: "Hard Luck",
    year: 1921,
    director: "Buster Keaton",
    rating: 6,
  },
  {
    id: 62,
    title: "The High Sign",
    year: 1921,
    director: "Buster Keaton",
    rating: 7,
  },
  {
    id: 63,
    title: "The Goat",
    year: 1921,
    director: "Buster Keaton",
    rating: 6,
  },
  {
    id: 64,
    title: "Dreams of the Rarebit Fiend: The Pet",
    year: 1921,
    director: "Winsor McCay",
    rating: 8,
  },
  {
    id: 65,
    title: "The Play House",
    year: 1921,
    director: "Buster Keaton",
    rating: 7,
  },
  {
    id: 66,
    title: "The Mechanical Man",
    year: 1921,
    director: "André Deed",
    rating: 5,
  },
  {
    id: 67,
    title: "The Boat",
    year: 1921,
    director: "Buster Keaton",
    rating: 6,
  },
  {
    id: 68,
    title: "The Paleface",
    year: 1922,
    director: "Buster Keaton",
    rating: 6,
  },
  {
    id: 69,
    title: "The Nut",
    year: 1921,
    director: "Theodore Reed",
    rating: 8,
  },
  {
    id: 70,
    title: "Shattered",
    year: 1921,
    director: "Lupu Pick",
    rating: 7,
  },
  {
    id: 72,
    title: "The Wildcat",
    year: 1921,
    director: "Ernst Lubitsch",
    rating: 6,
  },
  {
    id: 73,
    title: "Dream Street",
    year: 1921,
    director: "D.W. Griffith",
    rating: 6,
  },
  {
    id: 74,
    title: "Seven Years Bad Luck",
    year: 1921,
    director: "Max Linder",
    rating: 6,
  },
  {
    id: 75,
    title: "El Dorado",
    year: 1921,
    director: "Marcel L'Herbier",
    rating: 7,
  },
  {
    id: 77,
    title: "Orphans of the Storm",
    year: 1921,
    director: "D.W. Griffith",
    rating: 5,
  },
  {
    id: 78,
    title: "The Blot",
    year: 1921,
    director: "Lois Weber",
    rating: 5,
  },
  {
    id: 79,
    title: "Backstairs",
    year: 1921,
    director: "Paul Leni",
    rating: 8,
  },
  {
    id: 80,
    title: "Growth of the Soil",
    year: 1921,
    director: "Gunnar Sommerfeldt",
    rating: 7,
  },
  {
    id: 81,
    title: "Tol'able David",
    year: 1921,
    director: "Henry King",
    rating: 6,
  },
  {
    id: 82,
    title: "Dr. Mabuse, the Gambler",
    year: 1922,
    director: "Fritz Lang",
    rating: 8,
  },
  {
    id: 83,
    title: "Nosferatu",
    year: 1922,
    director: "F. W. Murnau",
    rating: 6,
  },
  {
    id: 84,
    title: "Nanook of the North",
    year: 1922,
    director: "Robert Flaherty",
    rating: 5,
  },
  {
    id: 85,
    title: "Monte Cristo",
    year: 1922,
    director: "Emmett J. Flynn",
    rating: 5,
  },
  {
    id: 86,
    title: "Once Upon a Time",
    year: 1922,
    director: "Carl Theodor Dreyer",
    rating: 5,
  },
  {
    id: 87,
    title: "Lorna Doone",
    year: 1922,
    director: "Maurice Tourneur",
    rating: 5,
  },
  {
    id: 88,
    title: "Blood and Sand",
    year: 1922,
    director: "Fred Niblo",
    rating: 6,
  },
  {
    id: 89,
    title: "The Woman from Nowhere",
    year: 1922,
    director: " Louis Delluc",
    rating: 7,
  },
  {
    id: 90,
    title: "The Burning Soil",
    year: 1922,
    director: "F. W. Murnau",
    rating: 5,
  },
  {
    id: 91,
    title: "The Toll of the Sea",
    year: 1922,
    director: "Chester M. Franklin",
    rating: 5,
  },
  {
    id: 92,
    title: "The Mill",
    year: 1909,
    director: "Alfred Machin",
    rating: 7,
  },
  {
    id: 93,
    title: "The Oval Portrait",
    year: 1910,
    director: "Léonce Perret",
    rating: 8,
  },
  {
    id: 94,
    title: "AGGRO DR1FT",
    year: 2023,
    director: "Harmony Korine",
    rating: 8,
  },
  {
    id: 95,
    title: "The Feeling That the Time for Doing Something Has Passed",
    year: 2023,
    director: "Joanna Arnow",
    rating: 6,
  },
  {
    id: 96,
    title: "All of Us Strangers",
    year: 2023,
    director: "Andrew Haigh",
    rating: 5,
  },
  {
    id: 97,
    title: "The Holdovers",
    year: 2023,
    director: "Alexander Payne",
    rating: 5,
  },
  {
    id: 98,
    title: "Challengers",
    year: 2024,
    director: "Luca Guadagnino",
    rating: 7,
  },
  {
    id: 99,
    title: "The First Omen",
    year: 2024,
    director: "Arkasha Stevenson",
    rating: 5,
  },
  {
    id: 100,
    title: "Dungeons & Dragons: Honor Among Thieves",
    year: 2023,
    director: "John Francis Daley",
    rating: 5,
  },
  {
    id: 101,
    title: "Decision to Leave",
    year: 2022,
    director: "Park Chan-wook",
    rating: 6,
  },
  {
    id: 102,
    title: "The Humans",
    year: 2021,
    director: "Stephen Karam",
    rating: 6,
  },
  {
    id: 103,
    title: "The Nest",
    year: 2020,
    director: "Sean Durkin",
    rating: 8,
  },
  {
    id: 104,
    title: "Short Vacation",
    year: 2020,
    director: "Kwon Min-pyo",
    rating: 6,
  },
  {
    id: 105,
    title: "The Disciple",
    year: 2020,
    director: "Chaitanya Tamhane",
    rating: 5,
  },
  {
    id: 106,
    title: "Smiley Face Killers",
    year: 2020,
    director: "Tim Hunter",
    rating: 5,
  },
  {
    id: 106,
    title: "Possessor",
    year: 2020,
    director: "Brandon Cronenberg",
    rating: 7,
  },
  {
    id: 106,
    title: "The Empty Man",
    year: 2020,
    director: "David Prior",
    rating: 5,
  },
  {
    id: 106,
    title: "Once Upon a Time… in Hollywood",
    year: 2019,
    director: "Quentin Tarantino",
    rating: 7,
  },
  {
    id: 106,
    title: "Tommaso",
    year: 2019,
    director: "Abel Ferrara",
    rating: 6,
  },
  {
    id: 106,
    title: "Long Day's Journey Into Night",
    year: 2018,
    director: "Bi Gan",
    rating: 9,
  },
  {
    id: 106,
    title: "Classical Period",
    year: 2018,
    director: "Ted Fendt",
    rating: 8,
  },
  {
    id: 106,
    title: "Burning",
    year: 2018,
    director: "Lee Chang-dong",
    rating: 8,
  },
  {
    id: 106,
    title: "Madeline's Madeline",
    year: 2018,
    director: "Josephine Decker",
    rating: 6,
  },
  {
    id: 106,
    title: "Suspiria",
    year: 2018,
    director: "Luca Guadagnino",
    rating: 6,
  },
  {
    id: 106,
    title: "Chained for Life",
    year: 2018,
    director: "Aaron Schimberg",
    rating: 7,
  },
  {
    id: 106,
    title: "Vox Lux",
    year: 2018,
    director: "Brady Corbet",
    rating: 7,
  },
  {
    id: 106,
    title: "Hanagatami",
    year: 2017,
    director: "Nobuhiko Obayashi",
    rating: 9,
  },
  {
    id: 106,
    title: "On the Beach at Night Alone",
    year: 2017,
    director: "Hong Sang-soo",
    rating: 8,
  },
  {
    id: 106,
    title: "Western",
    year: 2017,
    director: "Valeska Grisebach",
    rating: 5,
  },
  {
    id: 106,
    title: "Loveless",
    year: 2017,
    director: "Andrey Zvyagintsev",
    rating: 7,
  },
  {
    id: 106,
    title: "Phantom Thread",
    year: 2017,
    director: "Paul Thomas Anderson",
    rating: 6,
  },
  {
    id: 106,
    title: "Paterson",
    year: 2016,
    director: "Jim Jarmusch",
    rating: 9,
  },
  {
    id: 106,
    title: "Yourself and Yours",
    year: 2016,
    director: "Hong Sang-soo",
    rating: 8,
  },
  {
    id: 106,
    title: "A Cure for Wellness",
    year: 2016,
    director: "Gore Verbinski",
    rating: 7,
  },
  {
    id: 106,
    title: "Nocturnal Animals",
    year: 2016,
    director: "Tom Ford",
    rating: 6,
  },
  {
    id: 106,
    title: "Cameraperson",
    year: 2016,
    director: "Kirsten Johnson",
    rating: 6,
  },
  {
    id: 106,
    title: "The Wailing",
    year: 2016,
    director: "Na Hong-jin",
    rating: 7,
  },
  {
    id: 106,
    title: "Dawson City: Frozen Time",
    year: 2016,
    director: "Bill Morrison",
    rating: 6,
  },
  {
    id: 106,
    title: "Mad Max: Fury Road",
    year: 2015,
    director: "George Miller",
    rating: 8,
  },
  {
    id: 106,
    title: "Cosmos",
    year: 2015,
    director: "Andrzej Żuławski",
    rating: 7,
  },
  {
    id: 106,
    title: "High-Rise",
    year: 2015,
    director: "Ben Wheatley",
    rating: 6,
  },
  {
    id: 106,
    title: "Blackhat",
    year: 2015,
    director: "Michael Mann",
    rating: 7,
  },
  {
    id: 106,
    title: "Kaili Blues",
    year: 2015,
    director: "Bi Gan",
    rating: 6,
  },
  {
    id: 106,
    title: "James White",
    year: 2015,
    director: "Josh Mond",
    rating: 6,
  },
  {
    id: 106,
    title: "Aloha",
    year: 2015,
    director: "Cameron Crowe",
    rating: 5,
  },
  {
    id: 106,
    title: "Nightcrawler",
    year: 2014,
    director: "Dan Gilroy",
    rating: 6,
  },
  {
    id: 106,
    title: "Listen Up Philip",
    year: 2014,
    director: "Alex Ross Perry",
    rating: 6,
  },
  {
    id: 106,
    title: "Upstream Color",
    year: 2013,
    director: "Shane Carruth",
    rating: 9,
  },
  {
    id: 106,
    title: "The Counselor",
    year: 2013,
    director: "Ridley Scott",
    rating: 6,
  },
  {
    id: 106,
    title: "Stoker",
    year: 2013,
    director: "Park Chan-wook",
    rating: 5,
  },
  {
    id: 106,
    title: "The Double",
    year: 2013,
    director: "Richard Ayoade",
    rating: 7,
  },
  {
    id: 106,
    title: "Snowpiercer",
    year: 2013,
    director: "Bong Joon-ho",
    rating: 6,
  },
  {
    id: 106,
    title: "Inside Llewyn Davis",
    year: 2013,
    director: "Joel Coen",
    rating: 6,
  },
  {
    id: 106,
    title: "Sun Don't Shine",
    year: 2012,
    director: "Amy Seimetz",
    rating: 7,
  },
  {
    id: 106,
    title: "To the Wonder",
    year: 2012,
    director: "Terrence Malick",
    rating: 5,
  },
  {
    id: 106,
    title: "Moonrise Kingdom",
    year: 2012,
    director: "Wes Anderson",
    rating: 6,
  },
  {
    id: 106,
    title: "The Lords of Salem",
    year: 2012,
    director: "Rob Zombie",
    rating: 7,
  },
  {
    id: 106,
    title: "The Master",
    year: 2012,
    director: "Paul Thomas Anderson",
    rating: 10,
  },
  {
    id: 106,
    title: "Like Someone in Love",
    year: 2012,
    director: "Abbas Kiarostami",
    rating: 9,
  },
  {
    id: 106,
    title: "Cosmopolis",
    year: 2012,
    director: "David Cronenberg",
    rating: 7,
  },
  {
    id: 106,
    title: "Martha Marcy May Marlene",
    year: 2011,
    director: "Sean Durkin",
    rating: 6,
  },
  {
    id: 106,
    title: "Margaret",
    year: 2011,
    director: "Kenneth Lonergan",
    rating: 8,
  },
  {
    id: 106,
    title: "Drive",
    year: 2011,
    director: "Nicolas Winding Refn",
    rating: 8,
  },
  {
    id: 106,
    title: "The Tree of Life",
    year: 2011,
    director: "Terrence Malick",
    rating: 7,
  },
  {
    id: 106,
    title: "Twilight Portrait",
    year: 2011,
    director: "Angelina Nikonova",
    rating: 6,
  },
  {
    id: 106,
    title: "Kill List",
    year: 2011,
    director: "Ben Wheatley",
    rating: 6,
  },
  {
    id: 106,
    title: "Cold Weather",
    year: 2010,
    director: "Aaron Katz",
    rating: 6,
  },
  {
    id: 106,
    title: "The Sleeping Beauty",
    year: 2010,
    director: "Catherine Breillat",
    rating: 6,
  },
  {
    id: 106,
    title: "Coraline",
    year: 2009,
    director: "Henry Selick",
    rating: 10,
  },
  {
    id: 106,
    title: "(500) Days of Summer",
    year: 2009,
    director: "Marc Webb",
    rating: 5,
  },
  {
    id: 106,
    title: "A Serious Man",
    year: 2009,
    director: "Joel Coen",
    rating: 7,
  },
  {
    id: 106,
    title: "Bad Lieutenant: Port of Call - New Orleans",
    year: 2009,
    director: "Werner Herzog",
    rating: 5,
  },
  {
    id: 106,
    title: "Halloween II",
    year: 2009,
    director: "Rob Zombie",
    rating: 6,
  },
  {
    id: 106,
    title: "A Single Man",
    year: 2009,
    director: "Tom Ford",
    rating: 7,
  },
  {
    id: 106,
    title: "Synecdoche, New York",
    year: 2008,
    director: "Charlie Kaufman",
    rating: 6,
  },
  {
    id: 106,
    title: "Speed Racer",
    year: 2008,
    director: "Lilly Wachowski",
    rating: 8,
  },
  {
    id: 106,
    title: "Afterschool",
    year: 2008,
    director: "Antonio Campos",
    rating: 7,
  },
  {
    id: 106,
    title: "Night and Day",
    year: 2008,
    director: "Hong Sang-soo",
    rating: 7,
  },
  {
    id: 106,
    title: "Burn After Reading",
    year: 2008,
    director: "Ethan Coen",
    rating: 6,
  },
  {
    id: 106,
    title: "Michael Clayton",
    year: 2007,
    director: "Tony Gilroy",
    rating: 5,
  },
  {
    id: 106,
    title: "4 Months, 3 Weeks and 2 Days",
    year: 2007,
    director: "Cristian Mungiu",
    rating: 6,
  },
  {
    id: 106,
    title: "Paranoid Park",
    year: 2007,
    director: "Gus Van Sant",
    rating: 7,
  },
  {
    id: 106,
    title: "Joshua",
    year: 2007,
    director: "George Ratliff",
    rating: 7,
  },
  {
    id: 106,
    title: "Silent Light",
    year: 2007,
    director: "Carlos Reygadas",
    rating: 7,
  },
  {
    id: 106,
    title: "Funny Games",
    year: 2007,
    director: "Michael Haneke",
    rating: 5,
  },
  {
    id: 106,
    title: "Shoot 'Em Up",
    year: 2007,
    director: "Michael Davis",
    rating: 5,
  },
  {
    id: 106,
    title: "Miami Vice",
    year: 2006,
    director: "Michael Mann",
    rating: 10,
  },
  {
    id: 106,
    title: "Children of Men",
    year: 2006,
    director: "Alfonso Cuarón",
    rating: 8,
  },
  {
    id: 106,
    title: "Pan's Labyrinth",
    year: 2006,
    director: "Guillermo del Toro",
    rating: 8,
  },
  {
    id: 106,
    title: "Inland Empire",
    year: 2006,
    director: "David Lynch",
    rating: 8,
  },
  {
    id: 106,
    title: "Simon Says",
    year: 2006,
    director: "William Dear",
    rating: 7,
  },
  {
    id: 106,
    title: "Black Christmas",
    year: 2006,
    director: "Glen Morgan",
    rating: 7,
  },
  {
    id: 106,
    title: "Domino",
    year: 2005,
    director: "Tony Scott",
    rating: 8,
  },
  {
    id: 106,
    title: "Last Days",
    year: 2005,
    director: "Gus Van Sant",
    rating: 6,
  },
  {
    id: 106,
    title: "The New World",
    year: 2005,
    director: "Terrence Malick",
    rating: 7,
  },
  {
    id: 106,
    title: "Charlie and the Chocolate Factory",
    year: 2005,
    director: "Tim Burton",
    rating: 10,
  },
  {
    id: 106,
    title: "Brick",
    year: 2005,
    director: "Rian Johnson",
    rating: 7,
  },
  {
    id: 106,
    title: "Mortuary",
    year: 2005,
    director: "Tobe Hooper",
    rating: 6,
  },
  {
    id: 106,
    title: "Tideland",
    year: 2005,
    director: "Terry Gilliam",
    rating: 6,
  },
  {
    id: 106,
    title: "The Puffy Chair",
    year: 2005,
    director: "Jay Duplass",
    rating: 7,
  },
  {
    id: 106,
    title: "Torque",
    year: 2004,
    director: "Joseph Kahn",
    rating: 5,
  },
  {
    id: 106,
    title: "Mindhunters",
    year: 2004,
    director: "Renny Harlin",
    rating: 7,
  },
  {
    id: 106,
    title: "The Village",
    year: 2004,
    director: "M. Night Shyamalan",
    rating: 5,
  },
  {
    id: 106,
    title: "Birth",
    year: 2004,
    director: "Jonathan Glazer",
    rating: 6,
  },
  {
    id: 106,
    title: "Hotel",
    year: 2004,
    director: "Jessica Hausner",
    rating: 7,
  },
  {
    id: 106,
    title: "Collateral",
    year: 2004,
    director: "Michael Mann",
    rating: 7,
  },
  {
    id: 106,
    title: "Primer",
    year: 2004,
    director: "Shane Carruth",
    rating: 6,
  },
  {
    id: 106,
    title: "Toolbox Murders",
    year: 2004,
    director: "Tobe Hooper",
    rating: 7,
  },
  {
    id: 106,
    title: "Eternal Sunshine of the Spotless Mind",
    year: 2004,
    director: "Michel Gondry",
    rating: 10,
  },
  {
    id: 106,
    title: "Mysterious Skin",
    year: 2004,
    director: "Gregg Araki",
    rating: 10,
  },
  {
    id: 106,
    title: "Kill Bill: Vol. 2",
    year: 2004,
    director: "Quentin Tarantino",
    rating: 9,
  },
  {
    id: 106,
    title: "Dogville",
    year: 2003,
    director: "Lars von Trier",
    rating: 7,
  },
  {
    id: 106,
    title: "Kill Bill: Vol. 1",
    year: 2003,
    director: "Quentin Tarantino",
    rating: 9,
  },
  {
    id: 106,
    title: "Down with Love",
    year: 2003,
    director: "Peyton Reed",
    rating: 7,
  },
  {
    id: 106,
    title: "Lost in Translation",
    year: 2003,
    director: "Sofia Coppola",
    rating: 6,
  },
  {
    id: 106,
    title: "Adaptation",
    year: 2002,
    director: "Spike Jonze",
    rating: 6,
  },
  {
    id: 106,
    title: "Femme Fatale",
    year: 2002,
    director: "Brian De Palma",
    rating: 7,
  },
  {
    id: 106,
    title: "Demonlover",
    year: 2002,
    director: "Olivier Assayas",
    rating: 10,
  },
  {
    id: 106,
    title: "FearDotCom",
    year: 2002,
    director: "William Malone",
    rating: 7,
  },
  {
    id: 106,
    title: "Oasis",
    year: 2002,
    director: "Lee Chang-dong",
    rating: 6,
  },
  {
    id: 106,
    title: "Donnie Darko",
    year: 2001,
    director: "Richard Kelly",
    rating: 10,
  },
  {
    id: 106,
    title: "Bully",
    year: 2001,
    director: "Larry Clark",
    rating: 7,
  },
  {
    id: 106,
    title: "Dagon",
    year: 2001,
    director: "Stuart Gordon",
    rating: 5,
  },
  {
    id: 106,
    title: "Storytelling",
    year: 2001,
    director: "Todd Solondz",
    rating: 6,
  },
  {
    id: 106,
    title: "Pulse",
    year: 2001,
    director: "Kiyoshi Kurosawa",
    rating: 5,
  },
  {
    id: 106,
    title: "Fat Girl",
    year: 2001,
    director: "Catherine Breillat",
    rating: 7,
  },
  {
    id: 106,
    title: "Trixie",
    year: 2000,
    director: "Alan Rudolph",
    rating: 7,
  },
  {
    id: 106,
    title: "In the Mood for Love",
    year: 2000,
    director: "Wong Kar-wai",
    rating: 8,
  },
  {
    id: 106,
    title: "Chopper",
    year: 2000,
    director: "Andrew Dominik",
    rating: 6,
  },
  {
    id: 106,
    title: "Fight Club",
    year: 1999,
    director: "David Fincher",
    rating: 10,
  },
  {
    id: 106,
    title: "Being John Malkovich",
    year: 1999,
    director: "Spike Jonze",
    rating: 9,
  },
  {
    id: 106,
    title: "Barren Illusion",
    year: 1999,
    director: "Kiyoshi Kurosawa",
    rating: 8,
  },
  {
    id: 106,
    title: "The Matrix",
    year: 1999,
    director: "Lilly Wachowski",
    rating: 7,
  },
  {
    id: 106,
    title: "Eyes Wide Shut",
    year: 1999,
    director: "Stanley Kubrick",
    rating: 5,
  },
  {
    id: 106,
    title: "Man of the Century",
    year: 1999,
    director: "Adam Abraham",
    rating: 6,
  },
  {
    id: 106,
    title: "8 ½ Women",
    year: 1999,
    director: "Peter Greenaway",
    rating: 8,
  },
  {
    id: 106,
    title: "Topsy-Turvy",
    year: 1999,
    director: "Mike Leigh",
    rating: 6,
  },
  {
    id: 106,
    title: "Breakfast of Champions",
    year: 1999,
    director: "Alan Rudolph",
    rating: 7,
  },
  {
    id: 106,
    title: "The Limey",
    year: 1999,
    director: "Steven Soderbergh",
    rating: 5,
  },
  {
    id: 106,
    title: "Ghost Dog: The Way of the Samurai",
    year: 1999,
    director: "Jim Jarmusch",
    rating: 5,
  },
  {
    id: 106,
    title: "My Best Fiend",
    year: 1999,
    director: "Werner Herzog",
    rating: 6,
  },
  {
    id: 106,
    title: "eXistenZ",
    year: 1999,
    director: "David Cronenberg",
    rating: 5,
  },
  {
    id: 106,
    title: "The Celebration",
    year: 1998,
    director: "Thomas Vinterberg",
    rating: 8,
  },
  {
    id: 106,
    title: "Besieged",
    year: 1998,
    director: "Bernardo Bertolucci",
    rating: 7,
  },
  {
    id: 106,
    title: "Run Lola Run",
    year: 1998,
    director: "Tom Tykwer",
    rating: 6,
  },
  {
    id: 106,
    title: "The Book of Life",
    year: 1998,
    director: "Hal Hartley",
    rating: 5,
  },
  {
    id: 106,
    title: "Afterglow",
    year: 1997,
    director: "Alan Rudolph",
    rating: 8,
  },
  {
    id: 106,
    title: "Level Five",
    year: 1997,
    director: "Chris Marker",
    rating: 7,
  },
  {
    id: 106,
    title: "Lost Highway",
    year: 1997,
    director: "David Lynch",
    rating: 7,
  },
  {
    id: 106,
    title: "The Blackout",
    year: 1997,
    director: "Abel Ferrara",
    rating: 7,
  },
  {
    id: 106,
    title: "Cure",
    year: 1997,
    director: "Kiyoshi Kurosawa",
    rating: 6,
  },
  {
    id: 106,
    title: "The House",
    year: 1997,
    director: "Šarūnas Bartas",
    rating: 6,
  },
  {
    id: 106,
    title: "Henry Fool",
    year: 1997,
    director: "Hal Hartley",
    rating: 5,
  },
  {
    id: 106,
    title: "Breaking the Waves",
    year: 1996,
    director: "Lars von Trier",
    rating: 5,
  },
  {
    id: 106,
    title: "Thinner",
    year: 1996,
    director: "Tom Holland",
    rating: 7,
  },
  {
    id: 106,
    title: "Irma Vep",
    year: 1996,
    director: "Olivier Assayas",
    rating: 8,
  },
  {
    id: 106,
    title: "The Phantom",
    year: 1996,
    director: "Simon Wincer",
    rating: 6,
  },
  {
    id: 106,
    title: "Safe",
    year: 1995,
    director: "Todd Haynes",
    rating: 9,
  },
  {
    id: 106,
    title: "Dead Man",
    year: 1995,
    director: "Jim Jarmusch",
    rating: 6,
  },
  {
    id: 106,
    title: "Maborosi",
    year: 1995,
    director: "Hirokazu Kore-eda",
    rating: 8,
  },
  {
    id: 106,
    title: "Strange Days",
    year: 1995,
    director: "Kathryn Bigelow",
    rating: 8,
  },
  {
    id: 106,
    title: "Twelve Monkeys",
    year: 1995,
    director: "Terry Gilliam",
    rating: 5,
  },
  {
    id: 106,
    title: "La Cérémonie",
    year: 1995,
    director: "Claude Chabrol",
    rating: 7,
  },
  {
    id: 106,
    title: "Castle Freak",
    year: 1995,
    director: "Stuart Gordon",
    rating: 7,
  },
  {
    id: 106,
    title: "Leaving Las Vegas",
    year: 1995,
    director: "Mike Figgis",
    rating: 5,
  },
  {
    id: 106,
    title: "Chungking Express",
    year: 1994,
    director: "Wong Kar-wai",
    rating: 9,
  },
  {
    id: 106,
    title: "Spanking the Monkey",
    year: 1994,
    director: "David O. Russell",
    rating: 8,
  },
  {
    id: 106,
    title: "Barcelona",
    year: 1994,
    director: "Whit Stillman",
    rating: 7,
  },
  {
    id: 106,
    title: "In the Mouth of Madness",
    year: 1994,
    director: "John Carpenter",
    rating: 5,
  },
  {
    id: 106,
    title: "Exotica",
    year: 1994,
    director: "Atom Egoyan",
    rating: 6,
  },
  {
    id: 106,
    title: "Rhythm Thief",
    year: 1994,
    director: "Matthew Harrison",
    rating: 6,
  },
  {
    id: 106,
    title: "Torment",
    year: 1994,
    director: "Claude Chabrol",
    rating: 6,
  },
  {
    id: 106,
    title: "Uncovered",
    year: 1994,
    director: "Jim McBride",
    rating: 6,
  },
  {
    id: 106,
    title: "True Lies",
    year: 1994,
    director: "James Cameron",
    rating: 5,
  },
  {
    id: 106,
    title: "Three Colours: White",
    year: 1994,
    director: "Krzysztof Kieślowski",
    rating: 5,
  },
  {
    id: 106,
    title: "Blue",
    year: 1993,
    director: "Derek Jarman",
    rating: 7,
  },
  {
    id: 106,
    title: "Naked",
    year: 1993,
    director: "Mike Leigh",
    rating: 8,
  },
  {
    id: 106,
    title: "Freaked",
    year: 1993,
    director: "Alex Winter",
    rating: 7,
  },
  {
    id: 106,
    title: "Three Colours: Blue",
    year: 1993,
    director: "Krzysztof Kieślowski",
    rating: 7,
  },
  {
    id: 106,
    title: "Wittgenstein",
    year: 1993,
    director: "Derek Jarman",
    rating: 6,
  },
  {
    id: 106,
    title: "Surviving Desire",
    year: 1992,
    director: "Hal Hartley",
    rating: 9,
  },
  {
    id: 106,
    title: "Bad Lieutenant",
    year: 1992,
    director: "Abel Ferrara",
    rating: 8,
  },
  {
    id: 106,
    title: "Unforgiven",
    year: 1992,
    director: "Clint Eastwood",
    rating: 6,
  },
  {
    id: 106,
    title: "Dr. Giggles",
    year: 1992,
    director: "Manny Coto",
    rating: 7,
  },
  {
    id: 106,
    title: "Simple Men",
    year: 1992,
    director: "Hal Hartley",
    rating: 10,
  },
  {
    id: 106,
    title: "Benny's Video",
    year: 1992,
    director: "Michael Haneke",
    rating: 7,
  },
  {
    id: 106,
    title: "Twin Peaks: Fire Walk with Me",
    year: 1992,
    director: "David Lynch",
    rating: 7,
  },
  {
    id: 106,
    title: "Equinox",
    year: 1992,
    director: "Alan Rudolph",
    rating: 6,
  },
  {
    id: 106,
    title: "Army of Darkness",
    year: 1992,
    director: "Sam Raimi",
    rating: 5,
  },
  {
    id: 106,
    title: "Nemesis",
    year: 1992,
    director: "Albert Pyun",
    rating: 5,
  },
  {
    id: 106,
    title: "The Cabinet of Dr. Ramirez",
    year: 1991,
    director: "Peter Sellars",
    rating: 10,
  },
  {
    id: 106,
    title: "The Double Life of Véronique",
    year: 1991,
    director: "Krzysztof Kieślowski",
    rating: 8,
  },
  {
    id: 106,
    title: "Naked Lunch",
    year: 1991,
    director: "David Cronenberg",
    rating: 7,
  },
  {
    id: 106,
    title: "The Rapture",
    year: 1991,
    director: "Michael Tolkin",
    rating: 6,
  },
  {
    id: 106,
    title: "Until the End of the World",
    year: 1991,
    director: "Wim Wenders",
    rating: 5,
  },
  {
    id: 106,
    title: "King of New York",
    year: 1990,
    director: "Abel Ferrara",
    rating: 7,
  },
  {
    id: 106,
    title: "Total Recall",
    year: 1990,
    director: "Paul Verhoeven",
    rating: 6,
  },
  {
    id: 106,
    title: "The Sheltering Sky",
    year: 1990,
    director: "Bernardo Bertolucci",
    rating: 8,
  },
  {
    id: 106,
    title: "The Golden Boat",
    year: 1990,
    director: "Raúl Ruiz",
    rating: 7,
  },
  {
    id: 106,
    title: "Days of Being Wild",
    year: 1990,
    director: "Wong Kar-wai",
    rating: 7,
  },
  {
    id: 106,
    title: "The Exorcist III",
    year: 1990,
    director: "William Peter Blatty",
    rating: 7,
  },
  {
    id: 106,
    title: "Metropolitan",
    year: 1990,
    director: "Whit Stillman",
    rating: 10,
  },
  {
    id: 106,
    title: "Miami Blues",
    year: 1990,
    director: "George Armitage",
    rating: 7,
  },
  {
    id: 106,
    title: "Love at Large",
    year: 1990,
    director: "Alan Rudolph",
    rating: 6,
  },
  {
    id: 106,
    title: "Wild at Heart",
    year: 1990,
    director: "David Lynch",
    rating: 6,
  },
  {
    id: 106,
    title: "Trust",
    year: 1990,
    director: "Hal Hartley",
    rating: 6,
  },
  {
    id: 106,
    title: "The Guardian",
    year: 1990,
    director: "William Friedkin",
    rating: 5,
  },
  {
    id: 106,
    title: "Dekalog",
    year: 1989,
    director: "Krzysztof Kieślowski",
    rating: 9,
  },
  {
    id: 106,
    title: "The Cook, the Thief, His Wife & Her Lover",
    year: 1989,
    director: "Peter Greenaway",
    rating: 8,
  },
  {
    id: 106,
    title: "sex, lies, and videotape",
    year: 1989,
    director: "Steven Soderbergh",
    rating: 7,
  },
  {
    id: 106,
    title: "Twin Peaks: Northwest Passage",
    year: 1989,
    director: "David Lynch",
    rating: 8,
  },
  {
    id: 106,
    title: "Elephant",
    year: 1989,
    director: "Alan Clarke",
    rating: 7,
  },
  {
    id: 106,
    title: "Meet the Feebles",
    year: 1989,
    director: "Peter Jackson",
    rating: 5,
  },
  {
    id: 106,
    title: "Mystery Train",
    year: 1989,
    director: "Jim Jarmusch",
    rating: 7,
  },
  {
    id: 106,
    title: "The Lair of the White Worm",
    year: 1988,
    director: "Ken Russell",
    rating: 10,
  },
  {
    id: 106,
    title: "Alice",
    year: 1988,
    director: "Jan Švankmajer",
    rating: 8,
  },
  {
    id: 106,
    title: "Landscape in the Mist",
    year: 1988,
    director: "Theo Angelopoulos",
    rating: 8,
  },
  {
    id: 106,
    title: "A Short Film About Love",
    year: 1988,
    director: "Krzysztof Kieślowski",
    rating: 7,
  },
  {
    id: 106,
    title: "The Vanishing",
    year: 1988,
    director: "George Sluizer",
    rating: 6,
  },
  {
    id: 106,
    title: "The Blob",
    year: 1988,
    director: "Chuck Russell",
    rating: 7,
  },
  {
    id: 106,
    title: "Vampire's Kiss",
    year: 1988,
    director: "Robert Bierman",
    rating: 6,
  },
  {
    id: 106,
    title: "Death Spa",
    year: 1988,
    director: "Michael Fischa",
    rating: 5,
  },
  {
    id: 106,
    title: "Alien from L.A.",
    year: 1988,
    director: "Albert Pyun",
    rating: 5,
  },
  {
    id: 106,
    title: "Angel Heart",
    year: 1987,
    director: "Alan Parker",
    rating: 8,
  },
  {
    id: 106,
    title: "The Cry of the Owl",
    year: 1987,
    director: "Claude Chabrol",
    rating: 7,
  },
  {
    id: 106,
    title: "Walker",
    year: 1987,
    director: "Alex Cox",
    rating: 7,
  },
  {
    id: 106,
    title: "Ishtar",
    year: 1987,
    director: "Elaine May",
    rating: 5,
  },
  {
    id: 106,
    title: "Anguish",
    year: 1987,
    director: "Bigas Luna",
    rating: 6,
  },
  {
    id: 106,
    title: "Cobra Verde",
    year: 1987,
    director: "Werner Herzog",
    rating: 5,
  },
  {
    id: 106,
    title: "Blue Velvet",
    year: 1986,
    director: "David Lynch",
    rating: 10,
  },
  {
    id: 106,
    title: "Caravaggio",
    year: 1986,
    director: "Derek Jarman",
    rating: 8,
  },
  {
    id: 106,
    title: "From Beyond",
    year: 1986,
    director: "Stuart Gordon",
    rating: 7,
  },
  {
    id: 106,
    title: "Sleepwalk",
    year: 1986,
    director: "Sara Driver",
    rating: 6,
  },
  {
    id: 106,
    title: "The Big Easy",
    year: 1986,
    director: "Jim McBride",
    rating: 6,
  },
  {
    id: 106,
    title: "The Texas Chainsaw Massacre 2",
    year: 1986,
    director: "Tobe Hooper",
    rating: 7,
  },
  {
    id: 106,
    title: "8 Million Ways to Die",
    year: 1986,
    director: "Hal Ashby",
    rating: 5,
  },
  {
    id: 106,
    title: "Mauvais Sang",
    year: 1986,
    director: "Leos Carax",
    rating: 10,
  },
  {
    id: 106,
    title: "Return to Oz",
    year: 1985,
    director: "Walter Murch",
    rating: 10,
  },
  {
    id: 106,
    title: "Tampopo",
    year: 1985,
    director: "Jūzō Itami",
    rating: 7,
  },
  {
    id: 106,
    title: "Rendez-vous",
    year: 1985,
    director: "André Téchiné",
    rating: 7,
  },
  {
    id: 106,
    title: "After Hours",
    year: 1985,
    director: "Martin Scorsese",
    rating: 8,
  },
  {
    id: 106,
    title: "To Live and Die in L.A.",
    year: 1985,
    director: "William Friedkin",
    rating: 6,
  },
  {
    id: 106,
    title: "A Zed & Two Noughts",
    year: 1985,
    director: "Peter Greenaway",
    rating: 7,
  },
  {
    id: 106,
    title: "Phenomena",
    year: 1985,
    director: "Dario Argento",
    rating: 7,
  },
  {
    id: 106,
    title: "The Stuff",
    year: 1985,
    director: "Larry Cohen",
    rating: 6,
  },
  {
    id: 106,
    title: "Crime Wave",
    year: 1985,
    director: "John Paizs",
    rating: 5,
  },
  {
    id: 106,
    title: "Choose Me",
    year: 1984,
    director: "Alan Rudolph",
    rating: 7,
  },
  {
    id: 106,
    title: "The Hit",
    year: 1984,
    director: "Stephen Frears",
    rating: 6,
  },
  {
    id: 106,
    title: "The Adventures of Buckaroo Banzai",
    year: 1984,
    director: "W.D. Richter",
    rating: 5,
  },
  {
    id: 106,
    title: "Body Double",
    year: 1984,
    director: "Brian De Palma",
    rating: 5,
  },
  {
    id: 106,
    title: "City of Pirates",
    year: 1983,
    director: "Raúl Ruiz",
    rating: 8,
  },
  {
    id: 106,
    title: "Nostalgia",
    year: 1983,
    director: "Andrei Tarkovsky",
    rating: 7,
  },
  {
    id: 106,
    title: "Breathless",
    year: 1983,
    director: "Jim McBride",
    rating: 10,
  },
  {
    id: 106,
    title: "Psycho II",
    year: 1983,
    director: "Richard Franklin",
    rating: 7,
  },
  {
    id: 106,
    title: "El sur",
    year: 1983,
    director: "Víctor Erice",
    rating: 7,
  },
  {
    id: 106,
    title: "Videodrome",
    year: 1983,
    director: "David Cronenberg",
    rating: 6,
  },
  {
    id: 106,
    title: "Christine",
    year: 1983,
    director: "John Carpenter",
    rating: 5,
  },
  {
    id: 106,
    title: "The 4th Man",
    year: 1983,
    director: "Paul Verhoeven",
    rating: 5,
  },
  {
    id: 106,
    title: "Blade Runner",
    year: 1982,
    director: "Ridley Scott",
    rating: 5,
  },
  {
    id: 106,
    title: "The Thing",
    year: 1982,
    director: "John Carpenter",
    rating: 5,
  },
  {
    id: 106,
    title: "Fitzcarraldo",
    year: 1982,
    director: "Werner Herzog",
    rating: 6,
  },
  {
    id: 106,
    title: "Poltergeist",
    year: 1982,
    director: "Tobe Hooper",
    rating: 6,
  },
  {
    id: 106,
    title: "Fanny and Alexander",
    year: 1982,
    director: "Ingmar Bergman",
    rating: 9,
  },
  {
    id: 106,
    title: "Liquid Sky",
    year: 1982,
    director: "Slava Tsukerman",
    rating: 5,
  },
  {
    id: 106,
    title: "Cutter's Way",
    year: 1981,
    director: "Ivan Passer",
    rating: 8,
  },
  {
    id: 106,
    title: "Blow Out",
    year: 1981,
    director: "Brian De Palma",
    rating: 6,
  },
  {
    id: 106,
    title: "Wolfen",
    year: 1981,
    director: "Michael Wadleigh",
    rating: 7,
  },
  {
    id: 106,
    title: "Mad Max 2",
    year: 1981,
    director: "George Miller",
    rating: 6,
  },
  {
    id: 106,
    title: "The Secret of the Third Planet",
    year: 1981,
    director: "Roman Kachanov",
    rating: 7,
  },
  {
    id: 106,
    title: "Thief",
    year: 1981,
    director: "Michael Mann",
    rating: 5,
  },
  {
    id: 106,
    title: "Escape from New York",
    year: 1981,
    director: "John Carpenter",
    rating: 7,
  },
  {
    id: 106,
    title: "Ms .45",
    year: 1981,
    director: "Abel Ferrara",
    rating: 6,
  },
  {
    id: 106,
    title: "Possession",
    year: 1981,
    director: "Andrzej Żuławski",
    rating: 6,
  },
  {
    id: 106,
    title: "One from the Heart",
    year: 1981,
    director: "Francis Ford Coppola",
    rating: 5,
  },
  {
    id: 106,
    title: "From the Life of the Marionettes",
    year: 1980,
    director: "Ingmar Bergman",
    rating: 7,
  },
  {
    id: 106,
    title: "Atlantic City",
    year: 1980,
    director: "Louis Malle",
    rating: 7,
  },
  {
    id: 106,
    title: "The Constant Factor",
    year: 1980,
    director: "Krzysztof Zanussi",
    rating: 8,
  },
  {
    id: 106,
    title: "The Shining",
    year: 1980,
    director: "Stanley Kubrick",
    rating: 6,
  },
  {
    id: 106,
    title: "The Changeling",
    year: 1980,
    director: "Peter Medak",
    rating: 6,
  },
  {
    id: 106,
    title: "Céleste",
    year: 1980,
    director: "Percy Adlon",
    rating: 6,
  },
  {
    id: 106,
    title: "Manhattan",
    year: 1979,
    director: "Woody Allen",
    rating: 8,
  },
  {
    id: 106,
    title: "Dead Mountaineer's Hotel",
    year: 1979,
    director: "Grigori Kromanov",
    rating: 7,
  },
  {
    id: 106,
    title: "Apocalypse Now",
    year: 1979,
    director: "Francis Ford Coppola",
    rating: 6,
  },
  {
    id: 106,
    title: "Days of Heaven",
    year: 1978,
    director: "Terrence Malick",
    rating: 9,
  },
  {
    id: 106,
    title: "Blue Collar",
    year: 1978,
    director: "Paul Schrader",
    rating: 6,
  },
  {
    id: 106,
    title: "Perceval",
    year: 1978,
    director: "Éric Rohmer",
    rating: 7,
  },
  {
    id: 106,
    title: "Remember My Name",
    year: 1978,
    director: "Alan Rudolph",
    rating: 6,
  },
  {
    id: 106,
    title: "Sorcerer",
    year: 1977,
    director: "William Friedkin",
    rating: 8,
  },
  {
    id: 106,
    title: "Stroszek",
    year: 1977,
    director: "Werner Herzog ",
    rating: 7,
  },
  {
    id: 106,
    title: "The American Friend",
    year: 1977,
    director: "Wim Wenders",
    rating: 7,
  },
  {
    id: 106,
    title: "Heart of Glass",
    year: 1976,
    director: "Werner Herzog",
    rating: 8,
  },
  {
    id: 106,
    title: "Welcome to L.A.",
    year: 1976,
    director: "Alan Rudolph",
    rating: 7,
  },
  {
    id: 106,
    title: "The Killing of a Chinese Bookie",
    year: 1976,
    director: "John Cassavetes",
    rating: 7,
  },
  {
    id: 106,
    title: "Eaten Alive",
    year: 1976,
    director: "Tobe Hooper",
    rating: 6,
  },
  {
    id: 106,
    title: "The Tenant",
    year: 1976,
    director: "Roman Polanski",
    rating: 7,
  },
  {
    id: 106,
    title: "Mirror",
    year: 1975,
    director: "Andrei Tarkovsky",
    rating: 10,
  },
  {
    id: 106,
    title: "The Passenger",
    year: 1975,
    director: "Michelangelo Antonioni",
    rating: 8,
  },
  {
    id: 106,
    title: "Shampoo",
    year: 1975,
    director: "Hal Ashby",
    rating: 7,
  },
  {
    id: 106,
    title: "Lisztomania",
    year: 1975,
    director: "Ken Russell",
    rating: 6,
  },
  {
    id: 106,
    title: "Night Moves",
    year: 1975,
    director: "Arthur Penn",
    rating: 7,
  },
  {
    id: 106,
    title: "Barry Lyndon",
    year: 1975,
    director: "Stanley Kubrick",
    rating: 7,
  },
  {
    id: 106,
    title: "Other People's Letters",
    year: 1975,
    director: "Ilya Averbakh",
    rating: 7,
  },
  {
    id: 106,
    title: "Wrong Move",
    year: 1975,
    director: "Wim Wenders",
    rating: 6,
  },
  {
    id: 106,
    title: "Picnic at Hanging Rock",
    year: 1975,
    director: "Peter Weir",
    rating: 5,
  },
  {
    id: 106,
    title: "The Texas Chain Saw Massacre",
    year: 1974,
    director: "Tobe Hooper",
    rating: 9,
  },
  {
    id: 106,
    title: "Chinatown",
    year: 1974,
    director: "Roman Polanski",
    rating: 7,
  },
  {
    id: 106,
    title: "Alice in the Cities",
    year: 1974,
    director: "Wim Wenders",
    rating: 7,
  },
  {
    id: 106,
    title: "Phantom of the Paradise",
    year: 1974,
    director: "Brian De Palma",
    rating: 8,
  },
  {
    id: 106,
    title: "Fangs",
    year: 1974,
    director: "Art Names",
    rating: 7,
  },
  {
    id: 106,
    title: "The Parallax View",
    year: 1974,
    director: "Alan J. Pakula",
    rating: 5,
  },
  {
    id: 106,
    title: "A Woman Under the Influence",
    year: 1974,
    director: "John Cassavetes",
    rating: 7,
  },
  {
    id: 106,
    title: "Badlands",
    year: 1973,
    director: "Terrence Malick",
    rating: 9,
  },
  {
    id: 106,
    title: "Paper Moon",
    year: 1973,
    director: "Peter Bogdanovich",
    rating: 6,
  },
  {
    id: 106,
    title: "The Spirit of the Beehive",
    year: 1973,
    director: "Víctor Erice",
    rating: 8,
  },
  {
    id: 106,
    title: "Illumination",
    year: 1973,
    director: "Krzysztof Zanussi",
    rating: 7,
  },
  {
    id: 106,
    title: "The Last Detail",
    year: 1973,
    director: "Hal Ashby",
    rating: 6,
  },
  {
    id: 106,
    title: "The Long Goodbye",
    year: 1973,
    director: "Robert Altman",
    rating: 6,
  },
  {
    id: 106,
    title: "High Plains Drifter",
    year: 1973,
    director: "Clint Eastwood",
    rating: 6,
  },
  {
    id: 106,
    title: "Aguirre, the Wrath of God",
    year: 1972,
    director: "Werner Herzog",
    rating: 5,
  },
  {
    id: 106,
    title: "The Discreet Charm of the Bourgeoisie",
    year: 1972,
    director: "Luis Buñuel",
    rating: 7,
  },
  {
    id: 106,
    title: "Avanti!",
    year: 1972,
    director: "Billy Wilder",
    rating: 7,
  },
  {
    id: 106,
    title: "What?",
    year: 1972,
    director: "Roman Polanski",
    rating: 9,
  },
  {
    id: 106,
    title: "Images",
    year: 1972,
    director: "Robert Altman",
    rating: 6,
  },
  {
    id: 106,
    title: "Wake in Fright",
    year: 1971,
    director: "Ted Kotcheff",
    rating: 8,
  },
  {
    id: 106,
    title: "Bleak Moments",
    year: 1971,
    director: "Mike Leigh",
    rating: 7,
  },
  {
    id: 106,
    title: "The Long Farewell",
    year: 1971,
    director: "Kira Muratova",
    rating: 7,
  },
  {
    id: 106,
    title: "Walkabout",
    year: 1971,
    director: "Nicolas Roeg",
    rating: 8,
  },
  {
    id: 106,
    title: "Glen and Randa",
    year: 1971,
    director: "Jim McBride",
    rating: 6,
  },
  {
    id: 106,
    title: "Valerie and Her Week of Wonders",
    year: 1970,
    director: "Jaromil Jireš",
    rating: 6,
  },
  {
    id: 106,
    title: "The Breach",
    year: 1970,
    director: "Claude Chabrol",
    rating: 7,
  },
  {
    id: 106,
    title: "The Butcher",
    year: 1970,
    director: "Claude Chabrol",
    rating: 8,
  },
  {
    id: 106,
    title: "The Conformist",
    year: 1970,
    director: "Bernardo Bertolucci",
    rating: 6,
  },
  {
    id: 106,
    title: "The Landlord",
    year: 1970,
    director: "Hal Ashby",
    rating: 5,
  },
  {
    id: 106,
    title: "Even Dwarfs Started Small",
    year: 1970,
    director: "Werner Herzog",
    rating: 6,
  },
  {
    id: 106,
    title: "Kes",
    year: 1969,
    director: "Ken Loach",
    rating: 6,
  },
  {
    id: 106,
    title: "The Cremator",
    year: 1969,
    director: "Juraj Herz",
    rating: 7,
  },
  {
    id: 106,
    title: "Venus in Furs",
    year: 1969,
    director: "Jesús Franco",
    rating: 6,
  },
  {
    id: 106,
    title: "Signs of Life",
    year: 1968,
    director: "Werner Herzog",
    rating: 7,
  },
  {
    id: 106,
    title: "if…",
    year: 1968,
    director: "Lindsay Anderson",
    rating: 5,
  },
  {
    id: 106,
    title: "Faces",
    year: 1968,
    director: "John Cassavetes",
    rating: 9,
  },
  {
    id: 106,
    title: "The Graduate",
    year: 1967,
    director: "Mike Nichols",
    rating: 6,
  },
  {
    id: 106,
    title: "July Rain",
    year: 1967,
    director: "Marlen Khutsiyev",
    rating: 8,
  },
  {
    id: 106,
    title: "David Holzman's Diary",
    year: 1967,
    director: "Jim McBride",
    rating: 7,
  },
  {
    id: 106,
    title: "Le Samouraï",
    year: 1967,
    director: "Jean-Pierre Melville",
    rating: 6,
  },
  {
    id: 106,
    title: "Belle de Jour",
    year: 1967,
    director: "Luis Buñuel",
    rating: 5,
  },
  {
    id: 106,
    title: "Point Blank",
    year: 1967,
    director: "John Boorman",
    rating: 6,
  },
  {
    id: 106,
    title: "The President's Analyst",
    year: 1967,
    director: "Theodore J. Flicker",
    rating: 6,
  },
  {
    id: 106,
    title: "Blow-Up",
    year: 1966,
    director: "Michelangelo Antonioni",
    rating: 9,
  },
  {
    id: 106,
    title: "Seconds",
    year: 1966,
    director: "John Frankenheimer",
    rating: 6,
  },
  {
    id: 106,
    title: "Persona",
    year: 1966,
    director: "Ingmar Bergman",
    rating: 5,
  },
  {
    id: 106,
    title: "Repulsion",
    year: 1965,
    director: "Roman Polanski",
    rating: 6,
  },
  {
    id: 106,
    title: "Red Desert",
    year: 1964,
    director: "Michelangelo Antonioni",
    rating: 8,
  },
  {
    id: 106,
    title: "Nothing But a Man",
    year: 1964,
    director: "Michael Roemer",
    rating: 7,
  },
  {
    id: 106,
    title: "The Soft Skin",
    year: 1964,
    director: "François Truffaut",
    rating: 6,
  },
  {
    id: 106,
    title: "Gertrud",
    year: 1964,
    director: "Carl Theodor Dreyer",
    rating: 5,
  },
  {
    id: 106,
    title: "The Servant",
    year: 1963,
    director: "Joseph Losey",
    rating: 8,
  },
  {
    id: 106,
    title: "The Birds",
    year: 1963,
    director: "Alfred Hitchcock",
    rating: 9,
  },
  {
    id: 106,
    title: "The Silence",
    year: 1963,
    director: "Ingmar Bergman",
    rating: 6,
  },
  {
    id: 106,
    title: "The Fire Within",
    year: 1963,
    director: "Louis Malle",
    rating: 5,
  },
  {
    id: 106,
    title: "America America",
    year: 1963,
    director: "Elia Kazan",
    rating: 6,
  },
  {
    id: 106,
    title: "The Trial",
    year: 1962,
    director: "Orson Welles",
    rating: 8,
  },
  {
    id: 106,
    title: "The Exterminating Angel",
    year: 1962,
    director: "Luis Buñuel",
    rating: 6,
  },
  {
    id: 106,
    title: "Splendor in the Grass",
    year: 1961,
    director: "Elia Kazan",
    rating: 9,
  },
  {
    id: 106,
    title: "La Notte",
    year: 1961,
    director: "Michelangelo Antonioni",
    rating: 6,
  },
  {
    id: 106,
    title: "The Good Girls",
    year: 1960,
    director: "Claude Chabrol",
    rating: 7,
  },
  {
    id: 106,
    title: "L'Avventura",
    year: 1960,
    director: "Michelangelo Antonioni",
    rating: 7,
  },
  {
    id: 106,
    title: "The Young One",
    year: 1960,
    director: "Luis Buñuel",
    rating: 6,
  },
  {
    id: 106,
    title: "Wild River",
    year: 1960,
    director: "Elia Kazan",
    rating: 8,
  },
  {
    id: 106,
    title: "Nazarin",
    year: 1959,
    director: "Luis Buñuel",
    rating: 7,
  },
  {
    id: 106,
    title: "Hiroshima Mon Amour",
    year: 1959,
    director: "Alain Resnais",
    rating: 8,
  },
  {
    id: 106,
    title: "The Cousins",
    year: 1959,
    director: "Claude Chabrol",
    rating: 6,
  },
  {
    id: 106,
    title: "End of Desire",
    year: 1958,
    director: "Alexandre Astruc",
    rating: 8,
  },
  {
    id: 106,
    title: "Written on the Wind",
    year: 1956,
    director: "Douglas Sirk",
    rating: 8,
  },
  {
    id: 106,
    title: "Baby Doll",
    year: 1956,
    director: "Elia Kazan",
    rating: 9,
  },
  {
    id: 106,
    title: "Smiles of a Summer Night",
    year: 1955,
    director: "Ingmar Bergman",
    rating: 7,
  },
  {
    id: 106,
    title: "Rebel Without a Cause",
    year: 1955,
    director: "Nicholas Ray",
    rating: 6,
  },
  {
    id: 106,
    title: "Ordet",
    year: 1955,
    director: "Carl Theodor Dreyer",
    rating: 9,
  },
  {
    id: 106,
    title: "The Lady Without Camelias",
    year: 1953,
    director: "Michelangelo Antonioni",
    rating: 7,
  },
  {
    id: 106,
    title: "Summer with Monika",
    year: 1953,
    director: "Ingmar Bergman",
    rating: 8,
  },
  {
    id: 106,
    title: "Orpheus",
    year: 1950,
    director: "Jean Cocteau",
    rating: 6,
  },
  {
    id: 106,
    title: "The Third Man",
    year: 1949,
    director: "Carol Reed",
    rating: 7,
  },
  {
    id: 106,
    title: "The Red Shoes",
    year: 1948,
    director: "Michael Powell",
    rating: 9,
  },
  {
    id: 106,
    title: "Black Narcissus",
    year: 1947,
    director: "Michael Powell",
    rating: 10,
  },
  {
    id: 106,
    title: "Beauty and the Beast",
    year: 1946,
    director: "Jean Cocteau",
    rating: 7,
  },
  {
    id: 106,
    title: "Les Dames du bois de Boulogne",
    year: 1945,
    director: "Robert Bresson",
    rating: 7,
  },
  {
    id: 106,
    title: "History Is Made at Night",
    year: 1937,
    director: "Frank Borzage",
    rating: 7,
  },
  {
    id: 106,
    title: "Captain Blood",
    year: 1935,
    director: "Michael Curtiz",
    rating: 7,
  },
  {
    id: 106,
    title: "Vampyr",
    year: 1932,
    director: "Carl Theodor Dreyer",
    rating: 7,
  },
  {
    id: 106,
    title: "Shanghai Express",
    year: 1932,
    director: "Josef von Sternberg",
    rating: 8,
  },
  {
    id: 106,
    title: "I Was Born, But…",
    year: 1932,
    director: "Yasujirō Ozu",
    rating: 6,
  },
  {
    id: 106,
    title: "M",
    year: 1931,
    director: "Fritz Lang",
    rating: 8,
  },
  {
    id: 106,
    title: "An American Tragedy",
    year: 1931,
    director: "Josef von Sternberg",
    rating: 7,
  },
  {
    id: 106,
    title: "La Chienne",
    year: 1931,
    director: "Jean Renoir",
    rating: 6,
  },
  {
    id: 106,
    title: "Morocco",
    year: 1930,
    director: "Josef von Sternberg",
    rating: 8,
  },
  {
    id: 106,
    title: "Man with a Movie Camera",
    year: 1929,
    director: "Dziga Vertov",
    rating: 8,
  },
  {
    id: 106,
    title: "Pandora's Box",
    year: 1929,
    director: "G.W. Pabst",
    rating: 7,
  },
  {
    id: 106,
    title: "The River",
    year: 1928,
    director: "Frank Borzage",
    rating: 7,
  },
  {
    id: 106,
    title: "The Docks of New York",
    year: 1928,
    director: "Josef von Sternberg",
    rating: 8,
  },
  {
    id: 106,
    title: "Sunrise: A Song of Two Humans",
    year: 1927,
    director: "F. W. Murnau",
    rating: 10,
  },
  {
    id: 106,
    title: "College",
    year: 1927,
    director: "Buster Keaton",
    rating: 7,
  },
  {
    id: 106,
    title: "The Unknown",
    year: 1927,
    director: "Tod Browning",
    rating: 6,
  },
  {
    id: 106,
    title: "Faust",
    year: 1926,
    director: "F. W. Murnau",
    rating: 7,
  },
  {
    id: 106,
    title: "Variety",
    year: 1925,
    director: "E.A. Dupont",
    rating: 7,
  },
  {
    id: 106,
    title: "Seven Chances",
    year: 1925,
    director: "Buster Keaton",
    rating: 7,
  },
  {
    id: 106,
    title: "Michael",
    year: 1924,
    director: "Carl Theodor Dreyer",
    rating: 7,
  },
  {
    id: 106,
    title: "Girl Shy",
    year: 1924,
    director: "Sam Taylor",
    rating: 7,
  },
  {
    id: 106,
    title: "The Swallow and the Titmouse",
    year: 1924,
    director: "André Antoine",
    rating: 6,
  },
  {
    id: 106,
    title: "He Who Gets Slapped",
    year: 1924,
    director: "Victor Sjöström",
    rating: 6,
  },
  {
    id: 106,
    title: "The Hands of Orlac",
    year: 1924,
    director: "Robert Wiene",
    rating: 5,
  },
  {
    id: 106,
    title: "The Last Laugh",
    year: 1924,
    director: "F. W. Murnau",
    rating: 8,
  },
  {
    id: 106,
    title: "New Year's Eve",
    year: 1924,
    director: "Lupu Pick",
    rating: 5,
  },
  {
    id: 106,
    title: "L'Inhumaine",
    year: 1924,
    director: "Marcel L'Herbier",
    rating: 5,
  },
  {
    id: 106,
    title: "Sherlock, Jr.",
    year: 1924,
    director: "Buster Keaton",
    rating: 8,
  },
  {
    id: 106,
    title: "The Street",
    year: 1923,
    director: "Karl Grune",
    rating: 5,
  },
  {
    id: 106,
    title: "Cœur fidèle",
    year: 1923,
    director: "Jean Epstein",
    rating: 6,
  },
  {
    id: 106,
    title: "Safety Last!",
    year: 1923,
    director: "Fred C. Newmeyer",
    rating: 6,
  },
];
